spring:
  application:
    name: cloud-eureka

server:
  port: 8761

management:
  endpoints:
    web:
      exposure:
        include: "*"   #暴露所有的端点我们可以看到更多的服务实例相关信息，
    endpoint:
      health:
        show-details: ALWAYS   #health endpoint是否必须显示全部细节

eureka:
#  instance:
#    prefer-ip-address: true
#    hostname: erueka
  server:
    enable-self-preservation: false
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:${server.port}/eureka/


